apiVersion: v1
kind: Service
metadata:
  name: {{ include "echo-server.fullname" . }}
  labels:
{{ include "echo-server.labels" . | indent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.sourceRanges }}
  loadBalancerSourceRanges:
    {{- range .Values.service.sourceRanges }}
    - {{ . }}
    {{- end }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "echo-server.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
